package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Cleanup9x_Cleanup9y_Cleanup9z_Bbb'
in the project with id = 'Cleanup9x_Cleanup9y_Cleanup9z', and delete the patch script.
*/
create(RelativeId("Cleanup9x_Cleanup9y_Cleanup9z"), BuildType({
    id("Cleanup9x_Cleanup9y_Cleanup9z_Bbb")
    name = "bbb"
}))

