package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    cleanup {
        expect {
            keepRule {
                id = "KEEP_RULE_100"
                keepAtLeast = builds(4)
                applyToBuilds {
                    inBranches {
                        branchFilter = patterns("+:*project")
                    }
                    inPersonalBuilds = nonPersonal()
                    withStatus = successful()
                }
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = byPattern("+:**")
                }
                preserveArtifactsDependencies = true
            }
        }
        update {
            keepRule {
                id = "KEEP_RULE_100"
                keepAtLeast = builds(4)
                applyToBuilds {
                    inBranches {
                        branchFilter = patterns("+:*project")
                    }
                    inPersonalBuilds = nonPersonal()
                    withStatus = successful()
                }
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = byPattern("+:**")
                }
                preserveArtifactsDependencies = true
            }
        }
        expect {
            keepRule {
                id = "KEEP_RULE_101"
                keepAtLeast = builds(411)
                applyToBuilds {
                    inBranches {
                        branchFilter = patterns("+:*project11")
                    }
                    inPersonalBuilds = nonPersonal()
                    withStatus = successful()
                }
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = byPattern("+:**")
                }
                preserveArtifactsDependencies = true
            }
        }
        update {
            keepRule {
                id = "KEEP_RULE_101"
                keepAtLeast = builds(4112)
                applyToBuilds {
                    inBranches {
                        branchFilter = patterns("+:*project11")
                    }
                    inPersonalBuilds = nonPersonal()
                    withStatus = successful()
                }
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = byPattern("+:**")
                }
                preserveArtifactsDependencies = true
            }
        }
    }
}
