package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Cleanup9x_Cleanup9y'
in the project with id = 'Cleanup9x', and delete the patch script.
*/
create(RelativeId("Cleanup9x"), Project({
    id("Cleanup9x_Cleanup9y")
    name = "cleanup9y"
}))

