package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Cleanup9x_Cleanup9y_Cleanup9z'
in the project with id = 'Cleanup9x_Cleanup9y', and delete the patch script.
*/
create(RelativeId("Cleanup9x_Cleanup9y"), Project({
    id("Cleanup9x_Cleanup9y_Cleanup9z")
    name = "cleanup9z"

    cleanup {
        keep {
            id = "KEEP_RULE_119"
            keepAtLeast = allBuilds()
            applyToBuilds {
                inBranches("+:*own")
            }
            dataToKeep = everything()
            preserveArtifactsDependencies = true
        }
    }
}))

